# Welcome to Jekyll!
#

# Site settings
title: Real Time Earth
description: |
  A Strategic Initiative of Lamont Doherty
  Earth Observatory
owner: Lamont Doherty Earth Observatory # or company name
first_published: 2016 # if migrating another site, the year of your first publish
email: rte@ldeo.columbia.edu
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://rte.ldeo.columbia.edu" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/LamontEarth
  #github: https://github.com/<username>
  #linkedin-square: https://linkedin.com/in/<username>
  facebook-official: https://facebook.com/Lamont.Doherty
  #google-plus-square: https://plus.google.com/u/0/+<username>
  #email: /contact/
  #flickr:
  instagram: https://www.instagram.com/columbialamontearth/
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
